Fix Parser.parseDocuments
circe/circe-yaml pull request #346
Opened 2022-11-16 01:42 UTC by sideeffffect

fixes https://github.com/circe/circe-yaml/issues/343
closes https://github.com/circe/circe-yaml/pull/342
/cc @lucaviolanti

2022-11-16 11:49 UTC, lucaviolanti requested changes

2022-11-16 11:49 UTC, lucaviolanti commented on circe-yaml-v12/src/test/scala/io/circe/yaml/v12/ParserTests.scala
> +    // assert(result.swap.value.isInstanceOf[org.yaml.snakeyaml.scanner.ScannerException])
```suggestion
```

2022-11-16 11:49 UTC, lucaviolanti commented on circe-yaml-v12/src/test/scala/io/circe/yaml/v12/ParserTests.scala
> +     */
```suggestion
```

2022-11-16 11:49 UTC, lucaviolanti commented on circe-yaml-v12/src/test/scala/io/circe/yaml/v12/ParserTests.scala
> +     */
```suggestion
```

2022-11-16 11:49 UTC, lucaviolanti commented on circe-yaml-v12/src/test/scala/io/circe/yaml/v12/ParserTests.scala
> +    // assert(result.swap.value.isInstanceOf[org.yaml.snakeyaml.error.YAMLException])
```suggestion
```

2022-11-16 11:49 UTC, lucaviolanti commented on circe-yaml/src/test/scala/io/circe/yaml/ParserTests.scala
> +    // assert(result.swap.value.isInstanceOf[org.yaml.snakeyaml.scanner.ScannerException])
```suggestion
```

2022-11-16 11:49 UTC, lucaviolanti commented on circe-yaml/src/test/scala/io/circe/yaml/ParserTests.scala
> +     */
```suggestion
```

2022-11-16 11:49 UTC, lucaviolanti commented on circe-yaml/src/test/scala/io/circe/yaml/ParserTests.scala
> +    // assert(result.swap.value.isInstanceOf[org.yaml.snakeyaml.error.YAMLException])
```suggestion
```

2022-11-16 11:49 UTC, lucaviolanti commented on circe-yaml/src/test/scala/io/circe/yaml/ParserTests.scala
> +     */
```suggestion
```

2022-11-16 16:38 UTC, lucaviolanti approved these changes

2022-11-19 00:14 UTC, zarthross approved these changes
I think this looks fine.  I'll merge it in after https://github.com/circe/circe-yaml/pull/348 so we can start running more thorough CI on PRs.

2022-11-20 20:44 UTC, merged